export declare function addPortal(operation: any, portal: any): void;
export declare function swapPortal(operation: any, portal: any): void;
export declare function deletePortal(operation: any, portal: any): void;
export declare function deleteMarker(operation: any, marker: any, portal: any): void;
export declare function clearAllItems(operation: any): void;
export declare function clearAllLinks(operation: any): void;
export declare function clearAllMarkers(operation: any): void;
export declare function listenForAddedPortals(newPortal: any): void;
export declare function listenForPortalDetails(e: any): void;
export declare function getPortalDetails(guid: any): void;
export declare function loadFaked(operation: any, force?: boolean): void;
export declare function loadBlockerFaked(operation: any, force?: boolean): Promise<void>;
export declare function sendLocation(): void;
export declare function getAllPortalsOnScreen(operation: any): any[];
export declare function getAllPortalsLinked(operation: any, originPortal: any): any[];
export declare function testPortal(recursed?: boolean): any;
export declare function blockerAutomark(operation: any, first?: boolean): Promise<void>;
export declare function zoomToOperation(operation: any): void;
export declare function updateLocalOp(local: any, remote: any): Promise<boolean>;
export declare function fullSync(): Promise<void>;
export declare function syncOp(opID: any): Promise<void>;
export declare function deleteLocalOp(opname: any, opid: any): void;
export declare function resetCaches(): Promise<void>;
export declare function setMarkersToZones(): void;
export declare function setLinksToZones(): void;
